# Generated by Django 5.1.6 on 2025-03-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('os', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], max_length=10)),
            ],
        ),
    ]
