# Generated by Django 5.1.6 on 2025-03-07 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('_password', models.BinaryField()),
                ('port', models.PositiveIntegerField(blank=True, default=22, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('ssh_key', models.FileField(blank=True, null=True, upload_to='ssh_keys/')),
                ('passphrase', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WinRMCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('_password', models.BinaryField()),
                ('port', models.PositiveIntegerField(blank=True, default=5985, validators=[django.core.validators.MaxValueValidator(65535)])),
                ('ssl', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
