# Generated by Django 5.1.6 on 2025-03-07 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sshcredential_winrmcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ssh_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sshcredential'),
        ),
    ]
