# Generated by Django 5.1.6 on 2025-03-07 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_host_ssh_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='winrm_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.winrmcredential'),
        ),
    ]
