# Generated by Django 5.1.6 on 2025-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_host_winrm_credential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ssh_credential',
        ),
        migrations.RemoveField(
            model_name='host',
            name='winrm_credential',
        ),
        migrations.AddField(
            model_name='sshcredential',
            name='host',
            field=models.ManyToManyField(to='core.host'),
        ),
        migrations.AddField(
            model_name='winrmcredential',
            name='host',
            field=models.ManyToManyField(to='core.host'),
        ),
    ]
