# Generated by Django 5.1.6 on 2025-04-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sshcredential_host_alter_winrmcredential_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
