# Generated by Django 5.1.6 on 2025-05-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_host_ip_alter_host_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['id']},
        ),
    ]
