# Generated by Django 5.1.6 on 2025-03-10 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executecommand',
            name='status',
            field=models.CharField(choices=[('queue', 'В очереди'), ('progress', 'Выполняется'), ('error', 'Ошибка'), ('completed', 'Выполнено')], default='queue', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='executecommand',
            name='stderr',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='executecommand',
            name='stdout',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='executecommand',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executecommand',
            name='log',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
