# Generated by Django 5.1.6 on 2025-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sshcredential_host_alter_winrmcredential_host'),
        ('ops', '0002_executecommand_status_executecommand_stderr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executecommand',
            name='host',
        ),
        migrations.AddField(
            model_name='executecommand',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='core.host'),
        ),
    ]
