# Generated by Django 5.1.6 on 2025-03-17 05:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sshcredential_host_alter_winrmcredential_host'),
        ('ops', '0003_remove_executecommand_host_executecommand_hosts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log', models.JSONField(blank=True, default=dict, editable=False)),
                ('status', models.CharField(choices=[('queue', 'В очереди'), ('progress', 'Выполняется'), ('error', 'Ошибка'), ('completed', 'Выполнено')], default='queue', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(choices=[('smb', 'SMB'), ('sftp', 'SFTP')], max_length=10)),
                ('local_path', models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_path', message='Путь должен начинаться с / и содержать только буквы, цифры, точки, подчеркивания, дефисы и слеши.', regex='^(/[a-zA-Z0-9._\\-/]+)$')])),
                ('target_path', models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_path', message='Путь должен начинаться с / и содержать только буквы, цифры, точки, подчеркивания, дефисы и слеши.', regex='^(/[a-zA-Z0-9._\\-/]+)$')])),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hosts', models.ManyToManyField(blank=True, to='core.host')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
