# Generated by Django 5.1.6 on 2025-03-17 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0004_sendfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendfile',
            name='file',
            field=models.FileField(blank=True, upload_to='files_to_send/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='sendfile',
            name='local_path',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator(code='invalid_path', message='Путь должен начинаться с / и содержать только буквы, цифры, точки, подчеркивания, дефисы и слеши.', regex='^(/[a-zA-Z0-9._\\-/]+)$')]),
        ),
    ]
