# Generated by Django 5.1.6 on 2025-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_executecommand_sudo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executecommand',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sendfile',
            options={'ordering': ['-created_at']},
        ),
    ]
