# Generated by Django 5.1.6 on 2025-03-13 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_sshcredential_host_alter_winrmcredential_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtalonInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(editable=False)),
                ('path_to_instance', models.TextField(validators=[django.core.validators.RegexValidator(code='invalid_path', message='Путь должен начинаться с / и содержать только буквы, цифры, точки, подчеркивания, дефисы и слеши.', regex='^(/[a-zA-Z0-9._\\-/]+)$')])),
                ('version', models.CharField(editable=False, max_length=100)),
                ('tag', models.CharField(editable=False, max_length=20)),
                ('stand', models.CharField(editable=False, max_length=255)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etalon_instances', to='core.host')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='updates/%Y/%m/')),
                ('version', models.CharField(editable=False, max_length=100)),
                ('tag', models.CharField(editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
