# Generated by Django 5.1.6 on 2025-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etaloninstance',
            name='is_valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='etaloninstance',
            name='stand',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='etaloninstance',
            name='tag',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='etaloninstance',
            name='url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='etaloninstance',
            name='version',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
