# Generated by Django 5.1.6 on 2025-03-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0002_etaloninstance_is_valid_alter_etaloninstance_stand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etaloninstance',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='etaloninstance',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
