# Generated by Django 5.1.6 on 2025-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0003_etaloninstance_created_at_etaloninstance_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etaloninstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='etaloninstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
