# Generated by Django 5.1.6 on 2025-03-21 04:18

import django.core.validators
import etaupdater.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0004_alter_etaloninstance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatefile',
            name='file',
            field=models.FileField(upload_to='updates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gz']), etaupdater.validators.update_file_validator]),
        ),
    ]
