# Generated by Django 5.1.6 on 2025-03-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0006_prepareupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='etaloninstance',
            name='ready_to_update',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
