# Generated by Django 5.1.6 on 2025-05-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0007_etaloninstance_ready_to_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepareupdate',
            options={'ordering': ['-created_at']},
        ),
    ]
