# Generated by Django 5.1.6 on 2025-06-21 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0008_alter_prepareupdate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtalonUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log', models.JSONField(blank=True, default=dict, editable=False)),
                ('status', models.CharField(choices=[('queue', 'В очереди'), ('progress', 'Выполняется'), ('error', 'Ошибка'), ('completed', 'Выполнено')], default='queue', editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instances', models.ManyToManyField(to='etaupdater.etaloninstance')),
                ('update_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etaupdater.updatefile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
