# Generated by Django 5.1.6 on 2025-06-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0009_etalonupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='etaloninstance',
            name='docker_command',
            field=models.CharField(choices=[('docker-compose', 'Old'), ('docker compose', 'New')], default='docker compose', max_length=255),
        ),
    ]
