# Generated by Django 5.1.6 on 2025-09-23 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etaupdater', '0010_etaloninstance_docker_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrepareUpdate',
        ),
    ]
