name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log IN to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          registry: docker.kovalishin.ru
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: docker.kovalishin.ru/srvmanager:test-github
